version: '3'
services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  app:
    depends_on:
      - 'postgres'
    build: .
    command: bash -c "yarn install --check-files && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    ports:
      - '3000:3000'
    volumes:
      - '.:/politicosnamira'

volumes:
  postgres:
